version: "3"

services:
  mongodb:
    image: mongo
    # expose:
    #   - 27017
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run devel
